// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function EnsureAssets() {
  return window['go']['main']['App']['EnsureAssets']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ImportDatapackFolder() {
  return window['go']['main']['App']['ImportDatapackFolder']();
}

export function ImportDatapackZip() {
  return window['go']['main']['App']['ImportDatapackZip']();
}

export function OpenInstanceFolder() {
  return window['go']['main']['App']['OpenInstanceFolder']();
}

export function OpenProjectFolder() {
  return window['go']['main']['App']['OpenProjectFolder']();
}

export function OpenRecentProject(arg1) {
  return window['go']['main']['App']['OpenRecentProject'](arg1);
}

export function RunSetup(arg1) {
  return window['go']['main']['App']['RunSetup'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
