// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {instance} from '../models';

export function EnsureAssets():Promise<main.AssetsPayload>;

export function GetSettings():Promise<instance.Settings>;

export function GetStatus():Promise<main.StatusPayload>;

export function ImportDatapackFolder():Promise<string>;

export function ImportDatapackZip():Promise<string>;

export function OpenInstanceFolder():Promise<void>;

export function RunSetup(arg1:boolean):Promise<void>;

export function SaveSettings(arg1:instance.Settings):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
